name: MuleSoft CI Script

# Trigger settings
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Job settings
jobs:
  # build script
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build the Mule application with Maven.
        run: mvn clean package -DattachMuleSources
      
      - name: Upload the Mule application file to the release folder.
        run: java -jar app.jar -gitupload
        shell: bash
        working-directory: .github/script