name: MuleSoft CI staging process script

# Trigger settings
on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

# Job settings
jobs:
  # build script
  application-pre-build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build the Mule application with Maven.
        run: mvn clean package -DattachMuleSources
      
      - name: Upload the Mule application file to the release folder.
        run: java -jar app.jar -gitupload -gitpre true -gittoken ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        working-directory: .github/script